% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={TITULO},
  pdfauthor={Isabelle Archer, Lucía del Carmen Fito Fito, Iván Navarro Martínez, Ruben Saiz López (Grupo B1-08)},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{TITULO}
\author{Isabelle Archer, Lucía del Carmen Fito Fito, Iván Navarro
Martínez, Ruben Saiz López (Grupo B1-08)}
\date{2026-03-11}

\begin{document}
\maketitle

\section{Exploración y preparación de la
BBDD}\label{exploraciuxf3n-y-preparaciuxf3n-de-la-bbdd}

\subsection{Descripción y naturaleza de las
variables}\label{descripciuxf3n-y-naturaleza-de-las-variables}

\begin{verbatim}
##     pregnant glucose pressure triceps insulin mass pedigree age diabetes
## 4          1      89       66      23      94 28.1    0.167  21      neg
## 5          0     137       40      35     168 43.1    2.288  33      pos
## 7          3      78       50      32      88 31.0    0.248  26      pos
## 9          2     197       70      45     543 30.5    0.158  53      pos
## 15         5     166       72      19     175 25.8    0.587  51      pos
## 17         0     118       84      47     230 45.8    0.551  31      pos
## 19         1     103       30      38      83 43.3    0.183  33      neg
## 20         1     115       70      30      96 34.6    0.529  32      pos
## 21         3     126       88      41     235 39.3    0.704  27      neg
## 25        11     143       94      33     146 36.6    0.254  51      pos
## 26        10     125       70      26     115 31.1    0.205  41      pos
## 28         1      97       66      15     140 23.2    0.487  22      neg
## 29        13     145       82      19     110 22.2    0.245  57      neg
## 32         3     158       76      36     245 31.6    0.851  28      pos
## 33         3      88       58      11      54 24.8    0.267  22      neg
## 36         4     103       60      33     192 24.0    0.966  33      neg
## 40         4     111       72      47     207 37.1    1.390  56      pos
## 44         9     171      110      24     240 45.4    0.721  54      pos
## 51         1     103       80      11      82 19.4    0.491  22      neg
## 52         1     101       50      15      36 24.2    0.526  26      neg
## 53         5      88       66      21      23 24.4    0.342  30      neg
## 54         8     176       90      34     300 33.7    0.467  58      pos
## 55         7     150       66      42     342 34.7    0.718  42      neg
## 57         7     187       68      39     304 37.7    0.254  41      pos
## 60         0     105       64      41     142 41.5    0.173  22      neg
## 64         2     141       58      34     128 25.4    0.699  24      neg
## 69         1      95       66      13      38 19.6    0.334  25      neg
## 70         4     146       85      27     100 28.9    0.189  27      neg
## 71         2     100       66      20      90 32.9    0.867  28      pos
## 72         5     139       64      35     140 28.6    0.411  26      neg
## 74         4     129       86      20     270 35.1    0.231  23      neg
## 83         7      83       78      26      71 29.3    0.767  36      neg
## 86         2     110       74      29     125 32.4    0.698  27      neg
## 88         2     100       68      25      71 38.5    0.324  26      neg
## 89        15     136       70      32     110 37.1    0.153  43      pos
## 92         4     123       80      15     176 32.0    0.443  34      neg
## 93         7      81       78      40      48 46.7    0.261  42      neg
## 95         2     142       82      18      64 24.7    0.761  21      neg
## 96         6     144       72      27     228 33.9    0.255  40      neg
## 98         1      71       48      18      76 20.4    0.323  22      neg
## 99         6      93       50      30      64 28.7    0.356  23      neg
## 100        1     122       90      51     220 49.7    0.325  31      pos
## 104        1      81       72      18      40 26.6    0.283  24      neg
## 106        1     126       56      29     152 28.7    0.801  21      neg
## 108        4     144       58      28     140 29.5    0.287  37      neg
## 109        3      83       58      31      18 34.3    0.336  25      neg
## 110        0      95       85      25      36 37.4    0.247  24      pos
## 111        3     171       72      33     135 33.3    0.199  24      pos
## 112        8     155       62      26     495 34.0    0.543  46      pos
## 113        1      89       76      34      37 31.2    0.192  23      neg
## 115        7     160       54      32     175 30.5    0.588  39      pos
## 120        4      99       76      15      51 23.2    0.223  21      neg
## 121        0     162       76      56     100 53.2    0.759  25      pos
## 123        2     107       74      30     100 33.6    0.404  23      neg
## 126        1      88       30      42      99 55.0    0.496  26      pos
## 127        3     120       70      30     135 42.9    0.452  30      neg
## 128        1     118       58      36      94 33.3    0.261  23      neg
## 129        1     117       88      24     145 34.5    0.403  40      pos
## 131        4     173       70      14     168 29.7    0.361  33      pos
## 133        3     170       64      37     225 34.5    0.356  30      pos
## 135        2      96       68      13      49 21.1    0.647  26      neg
## 136        2     125       60      20     140 33.8    0.088  31      neg
## 137        0     100       70      26      50 30.8    0.597  21      neg
## 138        0      93       60      25      92 28.7    0.532  22      neg
## 140        5     105       72      29     325 36.9    0.159  28      neg
## 143        2     108       52      26      63 32.5    0.318  22      neg
## 145        4     154       62      31     284 32.8    0.237  23      neg
## 148        2     106       64      35     119 30.5    1.400  34      neg
## 151        1     136       74      50     204 37.4    0.399  24      neg
## 153        9     156       86      28     155 34.3    1.189  42      pos
## 154        1     153       82      42     485 40.6    0.687  23      neg
## 158        1     109       56      21     135 25.2    0.833  23      neg
## 159        2      88       74      19      53 29.0    0.229  22      neg
## 162        7     102       74      40     105 37.2    0.204  45      neg
## 163        0     114       80      34     285 44.2    0.167  27      neg
## 166        6     104       74      18     156 29.9    0.722  41      pos
## 170        3     111       90      12      78 28.4    0.495  29      neg
## 172        6     134       70      23     130 35.4    0.542  29      pos
## 174        1      79       60      42      48 43.5    0.678  23      neg
## 175        2      75       64      24      55 29.7    0.370  33      neg
## 176        8     179       72      42     130 32.7    0.719  36      pos
## 178        0     129      110      46     130 67.1    0.319  26      pos
## 182        0     119       64      18      92 34.9    0.725  23      neg
## 187        8     181       68      36     495 30.1    0.615  60      pos
## 188        1     128       98      41      58 32.0    1.321  33      pos
## 189        8     109       76      39     114 27.9    0.640  31      pos
## 190        5     139       80      35     160 31.6    0.361  25      pos
## 192        9     123       70      44      94 33.1    0.374  40      neg
## 196        5     158       84      41     210 39.4    0.395  29      pos
## 198        3     107       62      13      48 22.9    0.678  23      pos
## 199        4     109       64      44      99 34.8    0.905  26      pos
## 200        4     148       60      27     318 30.9    0.150  29      pos
## 204        2      99       70      16      44 20.4    0.235  27      neg
## 205        6     103       72      32     190 37.7    0.324  55      neg
## 207        8     196       76      29     280 37.5    0.605  57      pos
## 209        1      96       64      27      87 33.2    0.289  21      neg
## 214        0     140       65      26     130 42.6    0.431  24      pos
## 215        9     112       82      32     175 34.2    0.260  36      pos
## 216       12     151       70      40     271 41.8    0.742  38      pos
## 217        5     109       62      41     129 35.8    0.514  25      pos
## 218        6     125       68      30     120 30.0    0.464  32      neg
## 221        0     177       60      29     478 34.6    1.072  21      pos
## 224        7     142       60      33     190 28.8    0.687  61      neg
## 225        1     100       66      15      56 23.6    0.666  26      neg
## 226        1      87       78      27      32 34.6    0.101  22      neg
## 229        4     197       70      39     744 36.7    2.329  31      neg
## 230        0     117       80      31      53 45.2    0.089  24      neg
## 232        6     134       80      37     370 46.2    0.238  46      pos
## 233        1      79       80      25      37 25.4    0.583  22      neg
## 235        3      74       68      28      45 29.7    0.293  23      neg
## 237        7     181       84      21     192 35.9    0.586  51      pos
## 242        4      91       70      32      88 33.1    0.446  22      neg
## 244        6     119       50      22     176 27.1    1.318  33      pos
## 245        2     146       76      35     194 38.2    0.329  29      neg
## 248        0     165       90      33     680 52.3    0.427  23      neg
## 253        2      90       80      14      55 24.4    0.249  24      neg
## 255       12      92       62       7     258 27.6    0.926  44      pos
## 259        1     193       50      16     375 25.9    0.655  24      neg
## 260       11     155       76      28     150 33.3    1.353  51      pos
## 261        3     191       68      15     130 30.9    0.299  34      neg
## 266        5      96       74      18      67 33.6    0.997  43      neg
## 272        2     108       62      32      56 25.2    0.128  21      neg
## 274        1      71       78      50      45 33.2    0.422  21      neg
## 276        2     100       70      52      57 40.5    0.677  25      neg
## 278        0     104       64      23     116 27.8    0.454  23      neg
## 280        2     108       62      10     278 25.3    0.881  22      neg
## 282       10     129       76      28     122 35.9    0.280  39      neg
## 283        7     133       88      15     155 32.4    0.262  37      neg
## 287        5     155       84      44     545 38.7    0.619  34      neg
## 288        1     119       86      39     220 45.6    0.808  29      pos
## 289        4      96       56      17      49 20.8    0.340  26      neg
## 290        5     108       72      43      75 36.1    0.263  33      neg
## 291        0      78       88      29      40 36.9    0.434  21      neg
## 293        2     128       78      37     182 43.3    1.224  31      pos
## 294        1     128       48      45     194 40.5    0.613  24      pos
## 297        2     146       70      38     360 28.0    0.337  29      pos
## 298        0     126       84      29     215 30.7    0.520  24      neg
## 299       14     100       78      25     184 36.6    0.412  46      pos
## 302        2     144       58      33     135 31.6    0.422  25      pos
## 303        5      77       82      41      42 35.8    0.156  35      neg
## 306        2     120       76      37     105 39.7    0.215  29      neg
## 307       10     161       68      23     132 25.5    0.326  47      pos
## 308        0     137       68      14     148 24.8    0.143  21      neg
## 309        0     128       68      19     180 30.5    1.391  25      pos
## 310        2     124       68      28     205 32.9    0.875  30      pos
## 312        0     106       70      37     148 39.4    0.605  22      neg
## 313        2     155       74      17      96 26.6    0.433  27      pos
## 314        3     113       50      10      85 29.5    0.626  25      neg
## 316        2     112       68      22      94 34.1    0.315  26      neg
## 317        3      99       80      11      64 19.3    0.284  30      neg
## 319        3     115       66      39     140 38.1    0.150  28      neg
## 321        4     129       60      12     231 27.5    0.527  31      neg
## 324       13     152       90      33      29 26.8    0.731  43      pos
## 326        1     157       72      21     168 25.6    0.123  24      neg
## 327        1     122       64      32     156 35.1    0.692  30      pos
## 330        6     105       70      32      68 30.8    0.122  37      neg
## 332        2      87       58      16      52 32.7    0.166  25      neg
## 335        1      95       60      18      58 23.9    0.260  22      neg
## 336        0     165       76      43     255 47.9    0.259  26      neg
## 339        9     152       78      34     171 34.2    0.893  33      pos
## 341        1     130       70      13     105 25.9    0.472  22      neg
## 342        1      95       74      21      73 25.9    0.673  36      neg
## 346        8     126       88      36     108 38.5    0.349  49      neg
## 349        3      99       62      19      74 21.8    0.279  26      neg
## 354        1      90       62      12      43 27.2    0.580  24      neg
## 357        1     125       50      40     167 33.3    0.962  28      pos
## 359       12      88       74      40      54 35.3    0.378  48      neg
## 360        1     196       76      36     249 36.5    0.875  29      pos
## 361        5     189       64      33     325 31.2    0.583  29      pos
## 365        4     147       74      25     293 34.9    0.385  30      neg
## 366        5      99       54      28      83 34.0    0.499  30      neg
## 369        3      81       86      16      66 27.5    0.306  22      neg
## 370        1     133      102      28     140 32.8    0.234  45      pos
## 371        3     173       82      48     465 38.4    2.137  25      pos
## 373        0      84       64      22      66 35.8    0.545  21      neg
## 374        2     105       58      40      94 34.9    0.225  25      neg
## 375        2     122       52      43     158 36.2    0.816  28      neg
## 376       12     140       82      43     325 39.2    0.528  58      pos
## 377        0      98       82      15      84 25.2    0.299  22      neg
## 378        1      87       60      37      75 37.2    0.509  22      neg
## 380        0      93      100      39      72 43.4    1.021  35      neg
## 381        1     107       72      30      82 30.8    0.821  24      neg
## 383        1     109       60       8     182 25.4    0.947  21      neg
## 384        1      90       62      18      59 25.1    1.268  25      neg
## 385        1     125       70      24     110 24.3    0.221  25      neg
## 386        1     119       54      13      50 22.3    0.205  24      neg
## 389        5     144       82      26     285 32.0    0.452  58      pos
## 390        3     100       68      23      81 31.6    0.949  28      neg
## 391        1     100       66      29     196 32.0    0.444  42      neg
## 393        1     131       64      14     415 23.7    0.389  21      neg
## 394        4     116       72      12      87 22.1    0.463  37      neg
## 396        2     127       58      24     275 27.7    1.600  25      neg
## 397        3      96       56      34     115 24.7    0.944  39      neg
## 403        5     136       84      41      88 35.0    0.286  35      pos
## 406        2     123       48      32     165 42.1    0.520  26      neg
## 410        1     172       68      49     579 42.4    0.702  28      pos
## 412        1     112       72      30     176 34.4    0.528  25      neg
## 413        1     143       84      23     310 42.4    1.076  22      neg
## 414        1     143       74      22      61 26.2    0.256  21      neg
## 415        0     138       60      35     167 34.6    0.534  21      pos
## 416        3     173       84      33     474 35.7    0.258  22      pos
## 420        3     129       64      29     115 26.4    0.219  28      pos
## 421        1     119       88      41     170 45.3    0.507  26      neg
## 422        2      94       68      18      76 26.0    0.561  21      neg
## 425        8     151       78      32     210 42.9    0.516  36      pos
## 426        4     184       78      39     277 37.0    0.264  31      pos
## 428        1     181       64      30     180 34.1    0.328  38      pos
## 429        0     135       94      46     145 40.6    0.284  26      neg
## 430        1      95       82      25     180 35.0    0.233  43      pos
## 432        3      89       74      16      85 30.4    0.551  38      neg
## 433        1      80       74      11      60 30.0    0.527  22      neg
## 442        2      83       66      23      50 32.2    0.497  22      neg
## 443        4     117       64      27     120 33.2    0.230  24      neg
## 446        0     180       78      63      14 59.4    2.420  25      pos
## 447        1     100       72      12      70 25.3    0.658  28      neg
## 448        0      95       80      45      92 36.5    0.330  26      neg
## 449        0     104       64      37      64 33.6    0.510  22      pos
## 450        0     120       74      18      63 30.5    0.285  26      neg
## 451        1      82       64      13      95 21.2    0.415  23      neg
## 453        0      91       68      32     210 39.9    0.381  25      neg
## 455        2     100       54      28     105 37.8    0.498  24      neg
## 458        5      86       68      28      71 30.2    0.364  24      neg
## 459       10     148       84      48     237 37.6    1.001  51      pos
## 461        9     120       72      22      56 20.8    0.733  48      neg
## 463        8      74       70      40      49 35.3    0.705  39      neg
## 466        0     124       56      13     105 21.8    0.452  21      neg
## 467        0      74       52      10      36 27.8    0.269  22      neg
## 468        0      97       64      36     100 36.8    0.600  25      neg
## 470        6     154       78      41     140 46.1    0.571  27      neg
## 477        2     105       80      45     191 33.7    0.711  29      pos
## 478        7     114       76      17     110 23.8    0.466  31      neg
## 479        8     126       74      38      75 25.9    0.162  39      neg
## 483        4      85       58      22      49 27.8    0.306  28      neg
## 484        0      84       82      31     125 38.2    0.233  23      neg
## 486        0     135       68      42     250 42.3    0.365  24      pos
## 487        1     139       62      41     480 40.7    0.536  21      neg
## 488        0     173       78      32     265 46.5    1.159  58      neg
## 491        2      83       65      28      66 36.8    0.629  24      neg
## 494        4     125       70      18     122 28.9    1.144  45      pos
## 498        2      81       72      15      76 30.1    0.547  25      neg
## 499        7     195       70      33     145 25.1    0.163  55      pos
## 500        6     154       74      32     193 29.3    0.839  39      neg
## 501        2     117       90      19      71 25.2    0.313  21      neg
## 504        7      94       64      25      79 33.3    0.738  41      neg
## 507        0     180       90      26      90 36.5    0.314  35      pos
## 508        1     130       60      23     170 28.6    0.692  21      neg
## 509        2      84       50      23      76 30.4    0.968  21      neg
## 512        0     139       62      17     210 22.1    0.207  21      neg
## 515        3      99       54      19      86 25.6    0.154  24      neg
## 516        3     163       70      18     105 31.6    0.268  28      pos
## 517        9     145       88      34     165 30.3    0.771  53      pos
## 520        6     129       90       7     326 19.6    0.582  60      neg
## 521        2      68       70      32      66 25.0    0.187  25      neg
## 522        3     124       80      33     130 33.2    0.305  26      neg
## 527        1      97       64      19      82 18.2    0.299  21      neg
## 528        3     116       74      15     105 26.3    0.107  24      neg
## 529        0     117       66      31     188 30.8    0.493  22      neg
## 531        2     122       60      18     106 29.8    0.717  22      neg
## 533        1      86       66      52      65 41.3    0.917  29      neg
## 535        1      77       56      30      56 33.3    1.251  24      neg
## 539        0     127       80      37     210 36.3    0.804  23      neg
## 541        8     100       74      40     215 39.4    0.661  43      pos
## 542        3     128       72      25     190 32.4    0.549  27      pos
## 544        4      84       90      23      56 39.5    0.159  25      neg
## 545        1      88       78      29      76 32.0    0.365  29      neg
## 546        8     186       90      35     225 34.5    0.423  37      pos
## 547        5     187       76      27     207 43.6    1.034  53      pos
## 548        4     131       68      21     166 33.1    0.160  28      neg
## 549        1     164       82      43      67 32.8    0.341  50      neg
## 552        3      84       68      30     106 31.9    0.591  25      neg
## 554        1      88       62      24      44 29.9    0.422  23      neg
## 555        1      84       64      23     115 36.9    0.471  28      neg
## 556        7     124       70      33     215 25.5    0.161  37      neg
## 562        0     198       66      32     274 41.3    0.502  28      pos
## 563        1      87       68      34      77 37.6    0.401  24      neg
## 564        6      99       60      19      54 26.9    0.497  32      neg
## 566        2      95       54      14      88 26.1    0.748  22      neg
## 567        1      99       72      30      18 38.6    0.412  21      neg
## 568        6      92       62      32     126 32.0    0.085  46      neg
## 569        4     154       72      29     126 31.3    0.338  37      neg
## 570        0     121       66      30     165 34.3    0.203  33      pos
## 573        3     111       58      31      44 29.5    0.430  22      neg
## 574        2      98       60      17     120 34.7    0.198  22      neg
## 575        1     143       86      30     330 30.1    0.892  23      neg
## 576        1     119       44      47      63 35.5    0.280  25      neg
## 585        8     124       76      24     600 28.7    0.687  52      pos
## 589        3     176       86      27     156 33.3    1.154  52      pos
## 592        2     112       78      50     140 39.4    0.175  24      neg
## 594        2      82       52      22     115 28.5    1.699  25      neg
## 595        6     123       72      45     230 33.6    0.733  34      neg
## 596        0     188       82      14     185 32.0    0.682  22      pos
## 598        1      89       24      19      25 27.8    0.559  21      neg
## 600        1     109       38      18     120 23.1    0.407  26      neg
## 604        7     150       78      29     126 35.2    0.692  54      pos
## 607        1     181       78      42     293 40.0    1.258  22      pos
## 608        1      92       62      25      41 19.5    0.482  25      neg
## 609        0     152       82      39     272 41.5    0.270  27      neg
## 610        1     111       62      13     182 24.0    0.138  23      neg
## 611        3     106       54      21     158 30.9    0.292  24      neg
## 612        3     174       58      22     194 32.9    0.593  36      pos
## 613        7     168       88      42     321 38.2    0.787  40      pos
## 615       11     138       74      26     144 36.1    0.557  50      pos
## 618        2      68       62      13      15 20.1    0.257  23      neg
## 621        2     112       86      42     160 38.4    0.246  28      neg
## 624        0      94       70      27     115 43.5    0.347  21      neg
## 626        4      90       88      47      54 37.7    0.362  29      neg
## 632        0     102       78      40      90 34.5    0.238  24      neg
## 634        1     128       82      17     183 27.5    0.115  22      neg
## 638        2      94       76      18      66 31.6    0.649  23      neg
## 639        7      97       76      32      91 40.9    0.871  32      pos
## 640        1     100       74      12      46 19.5    0.149  28      neg
## 641        0     102       86      17     105 29.3    0.695  27      neg
## 645        3     103       72      30     152 27.6    0.730  27      neg
## 647        1     167       74      17     144 23.4    0.447  33      pos
## 648        0     179       50      36     159 37.8    0.455  22      pos
## 649       11     136       84      35     130 28.3    0.260  42      pos
## 651        1      91       54      25     100 25.2    0.234  23      neg
## 652        1     117       60      23     106 33.8    0.466  27      neg
## 653        5     123       74      40      77 34.1    0.269  28      neg
## 655        1     106       70      28     135 34.2    0.142  22      neg
## 656        2     155       52      27     540 38.7    0.240  25      pos
## 660        3      80       82      31      70 34.2    1.292  27      pos
## 663        8     167      106      46     231 37.6    0.165  43      pos
## 664        9     145       80      46     130 37.9    0.637  40      pos
## 666        1     112       80      45     132 34.8    0.217  24      neg
## 669        6      98       58      33     190 34.0    0.430  43      neg
## 670        9     154       78      30     100 30.9    0.164  45      neg
## 671        6     165       68      26     168 33.6    0.631  49      neg
## 673       10      68      106      23      49 35.5    0.285  47      neg
## 674        3     123      100      35     240 57.3    0.880  22      neg
## 680        2     101       58      17     265 24.2    0.614  23      neg
## 681        2      56       56      28      45 24.2    0.332  22      neg
## 683        0      95       64      39     105 44.6    0.366  22      neg
## 686        2     129       74      26     205 33.2    0.591  25      neg
## 689        1     140       74      26     180 24.1    0.828  23      neg
## 690        1     144       82      46     180 46.1    0.335  46      pos
## 693        2     121       70      32      95 39.1    0.886  23      neg
## 694        7     129       68      49     125 38.5    0.439  43      pos
## 696        7     142       90      24     480 30.4    0.128  43      pos
## 697        3     169       74      19     125 29.9    0.268  31      pos
## 699        4     127       88      11     155 34.5    0.598  28      neg
## 701        2     122       76      27     200 35.9    0.483  26      neg
## 705        4     110       76      20     100 28.4    0.118  27      neg
## 708        2     127       46      21     335 34.4    0.176  22      neg
## 710        2      93       64      32     160 38.0    0.674  23      pos
## 711        3     158       64      13     387 31.2    0.295  24      neg
## 714        0     134       58      20     291 26.4    0.352  21      neg
## 716        7     187       50      33     392 33.9    0.826  34      pos
## 717        3     173       78      39     185 33.8    0.970  31      pos
## 719        1     108       60      46     178 35.5    0.415  24      neg
## 722        1     114       66      36     200 38.1    0.289  21      neg
## 724        5     117       86      30     105 39.1    0.251  42      neg
## 727        1     116       78      29     180 36.1    0.496  25      neg
## 731        3     130       78      23      79 28.4    0.323  34      pos
## 733        2     174       88      37     120 44.5    0.646  24      pos
## 734        2     106       56      27     165 29.0    0.426  22      neg
## 737        0     126       86      27     120 27.4    0.515  21      neg
## 739        2      99       60      17     160 36.6    0.453  21      neg
## 741       11     120       80      37     150 42.3    0.785  48      pos
## 742        3     102       44      20      94 30.8    0.400  26      neg
## 743        1     109       58      18     116 28.5    0.219  22      neg
## 745       13     153       88      37     140 40.6    1.174  39      neg
## 746       12     100       84      33     105 30.0    0.488  46      neg
## 748        1      81       74      41      57 46.3    1.096  32      neg
## 749        3     187       70      22     200 36.4    0.408  36      pos
## 752        1     121       78      39      74 39.0    0.261  28      neg
## 754        0     181       88      44     510 43.3    0.222  26      pos
## 756        1     128       88      39     110 36.5    1.057  37      pos
## 761        2      88       58      26      16 28.4    0.766  22      neg
## 764       10     101       76      48     180 32.9    0.171  63      neg
## 766        5     121       72      23     112 26.2    0.245  30      neg
##     vegdiet cholesterol leptin  CRP
## 4        No      244.38  10.33 3.06
## 5       Yes      174.14   9.65 4.43
## 7        No      213.18   8.59 4.44
## 9        No      196.67   8.75 5.08
## 15       No      253.64   5.69 3.14
## 17      Yes      190.47   6.06 4.25
## 19       No      231.41   5.91 4.00
## 20      Yes      217.21  10.01 2.69
## 21       No      201.36  13.47 3.87
## 25       No      271.12  11.27 5.41
## 26       No      173.20   6.50 3.10
## 28       No      247.95   8.84 2.71
## 29       No      283.09   8.58 2.18
## 32      Yes      196.75   7.24 3.14
## 33       No      198.20   6.47 2.69
## 36       No      172.30   7.92 2.88
## 40      Yes      180.94  11.04 3.37
## 44       No      265.73   2.54 5.37
## 51       No      181.98  11.69 2.62
## 52      Yes      144.06   9.27 3.72
## 53      Yes      187.08   6.31 2.23
## 54       No      201.26   9.16 3.73
## 55      Yes      209.38   7.56 4.20
## 57       No      184.20   6.01 5.10
## 60      Yes      177.52   7.60 3.87
## 64      Yes      153.30  10.57 3.03
## 69      Yes      167.41   7.87 3.26
## 70       No      196.80  11.54 2.10
## 71       No      183.82  13.52 5.99
## 72       No      270.45  11.44 2.74
## 74       No      178.48   8.99 3.86
## 83       No      203.81   9.93 3.63
## 86      Yes      224.02   3.80 3.02
## 88      Yes      232.45   5.79 3.66
## 89      Yes      226.88   9.80 3.25
## 92       No      138.65  13.33 2.45
## 93       No      193.97  11.97 3.17
## 95       No      193.64   7.08 2.48
## 96       No      194.80   4.61 3.48
## 98      Yes      215.62   9.11 1.85
## 99       No      150.36   5.19 2.60
## 100      No      212.28   7.60 8.43
## 104      No      155.72   8.55 2.08
## 106     Yes      177.65   7.56 3.45
## 108     Yes      189.60   7.14 3.07
## 109     Yes      174.33   8.67 4.12
## 110      No      193.37   8.13 3.85
## 111      No      226.96   4.88 3.35
## 112     Yes      225.45   8.25 4.12
## 113      No      243.13   8.76 4.18
## 115      No      202.89   3.31 4.34
## 120      No      224.43   3.53 3.15
## 121     Yes      263.01   7.00 4.93
## 123     Yes      237.74  11.29 3.47
## 126      No      206.30   5.68 4.83
## 127     Yes      163.91  10.83 4.56
## 128      No      215.46   5.89 3.49
## 129     Yes      203.69   6.68 4.29
## 131     Yes      202.69   8.51 4.10
## 133      No      234.35   7.66 3.48
## 135     Yes      210.88  10.14 2.26
## 136      No      162.04  11.58 3.56
## 137      No      256.65   9.60 2.90
## 138      No      175.30  14.15 3.33
## 140      No      195.20  10.45 2.74
## 143      No      194.04  10.35 2.91
## 145     Yes      188.30   8.03 3.82
## 148      No      206.94  10.73 2.41
## 151      No      228.79  10.20 3.73
## 153      No      262.04  15.08 3.91
## 154     Yes      228.69   8.37 3.87
## 158     Yes      228.46  13.67 2.87
## 159      No      155.20  11.42 3.04
## 162     Yes      253.11   7.42 2.89
## 163     Yes      225.92   3.36 4.05
## 166      No      221.16   5.07 3.99
## 170      No      240.11   7.39 2.66
## 172      No      244.14   6.51 4.20
## 174      No      179.83   8.57 3.97
## 175      No      235.80   7.27 3.22
## 176      No      212.81  15.15 4.00
## 178     Yes      152.18   7.04 6.99
## 182      No      196.09   3.63 4.10
## 187      No      228.24   7.32 2.76
## 188      No      188.12   6.37 3.35
## 189      No      152.08   8.52 3.01
## 190     Yes      238.52   9.30 3.85
## 192      No      227.18  13.53 3.44
## 196     Yes      179.73   7.81 4.63
## 198      No      162.37  11.71 3.23
## 199      No      157.82   8.39 4.13
## 200      No      219.31  13.87 5.11
## 204      No      161.25  10.34 2.16
## 205      No      248.61  14.23 3.16
## 207      No      224.47   6.67 3.98
## 209      No      147.22   9.00 2.96
## 214      No      192.90   7.36 3.82
## 215      No      252.14   8.83 4.30
## 216      No      173.85   7.74 3.85
## 217     Yes      228.44  12.92 4.92
## 218      No      210.94   9.42 2.66
## 221      No      218.02   9.55 3.32
## 224      No      140.03   6.19 4.24
## 225     Yes      243.49   6.20 3.37
## 226      No      228.13   8.69 3.49
## 229     Yes      125.36   8.47 2.19
## 230      No      217.28  12.07 3.91
## 232      No      213.88   5.61 4.35
## 233     Yes      274.44   7.96 1.88
## 235     Yes      190.23  12.43 3.01
## 237      No      205.50   4.55 3.81
## 242      No      209.05   7.23 3.18
## 244      No      187.67   9.21 4.89
## 245      No      181.28   6.99 3.72
## 248     Yes      175.53   8.41 3.53
## 253      No      177.35  10.78 2.22
## 255      No      204.48   8.23 4.14
## 259     Yes      231.43  16.14 2.05
## 260     Yes      213.87   6.92 3.08
## 261      No      194.65   7.41 3.27
## 266      No      162.70   5.91 3.32
## 272      No      224.21  10.63 2.88
## 274      No      195.20   7.98 4.00
## 276      No      195.48  11.11 3.25
## 278      No      255.73   3.16 2.73
## 280      No      187.01  16.93 2.60
## 282      No      184.29   6.37 3.00
## 283      No      243.56  10.47 4.31
## 287      No      250.47  13.02 3.49
## 288      No      215.89   9.44 6.26
## 289      No      213.09   6.67 2.65
## 290     Yes      246.61   4.91 3.88
## 291      No      189.37   5.95 2.25
## 293     Yes      212.70  11.38 4.05
## 294      No      194.12  11.10 4.17
## 297     Yes      178.35  11.59 3.74
## 298      No      195.75   8.50 3.43
## 299     Yes      200.68   5.41 3.65
## 302      No      218.11   9.94 3.71
## 303      No      208.38  10.39 3.09
## 306      No      225.84   7.43 4.23
## 307      No      148.11   6.92 4.89
## 308     Yes      199.38  12.50 2.99
## 309     Yes      214.42   3.53 2.87
## 310     Yes      214.54   5.48 5.41
## 312      No      237.50   6.00 3.92
## 313     Yes      195.74  10.03 2.15
## 314      No      166.71   9.78 3.50
## 316     Yes      202.99  10.44 3.20
## 317      No      220.22  11.63 2.69
## 319      No      249.44  11.04 3.70
## 321     Yes      206.82  10.30 4.71
## 324      No      218.93   9.79 3.66
## 326     Yes      188.88  11.54 2.65
## 327      No      134.23   5.83 3.45
## 330      No      200.80   8.20 3.28
## 332     Yes      195.63  10.53 3.23
## 335      No      171.16   7.47 2.68
## 336     Yes      241.96  11.61 4.10
## 339     Yes      212.70   9.80 4.17
## 341      No      215.17   7.06 2.41
## 342     Yes      222.99   6.97 3.01
## 346      No      195.37   8.65 3.94
## 349     Yes      184.46  11.45 4.33
## 354     Yes      187.06   8.45 3.34
## 357     Yes      162.07   6.14 3.62
## 359      No      179.73  14.21 4.39
## 360      No      196.16   8.37 4.40
## 361      No      210.31   8.66 3.07
## 365      No      237.47   8.31 2.62
## 366     Yes      152.63   5.26 3.55
## 369      No      224.98   8.49 3.04
## 370      No      208.32   9.46 4.89
## 371     Yes      174.90   5.49 5.05
## 373      No      129.64  12.64 3.67
## 374     Yes      219.86   9.72 2.79
## 375      No      229.04  10.95 3.20
## 376     Yes      192.33   7.28 5.29
## 377      No      180.17  10.46 2.60
## 378      No      165.13   9.23 3.93
## 380      No      187.95   8.84 3.88
## 381      No      244.02  10.27 4.58
## 383     Yes      220.77   6.89 2.41
## 384      No      171.84   3.33 3.38
## 385     Yes      213.75  11.49 2.27
## 386      No      151.73  15.51 2.69
## 389      No      227.43   8.99 4.14
## 390      No      213.14   9.94 4.23
## 391     Yes      218.03  14.44 3.15
## 393      No      275.38  10.21 2.66
## 394      No      265.98  11.42 2.53
## 396      No      168.49   6.42 3.01
## 397     Yes      171.76  14.26 3.20
## 403     Yes      202.07   7.59 5.24
## 406      No      172.67   6.16 3.34
## 410      No      209.45  10.17 5.90
## 412     Yes      228.83   7.85 3.52
## 413      No      194.57  10.24 3.73
## 414     Yes      211.18   3.76 1.94
## 415      No      232.05   9.17 6.02
## 416      No      194.76  13.99 2.78
## 420      No      191.98   7.71 2.85
## 421      No      180.93   9.49 5.78
## 422      No      197.47  12.71 2.60
## 425     Yes      183.16  12.27 4.94
## 426      No      227.11  13.74 4.24
## 428      No      242.67  10.65 4.83
## 429      No      235.23   9.42 4.78
## 430     Yes      214.12  13.23 3.96
## 432      No      194.37  13.94 2.21
## 433      No      227.46   9.60 2.75
## 442      No      167.73   7.70 2.21
## 443      No      200.79  13.13 4.45
## 446      No      210.97  13.59 6.73
## 447      No      236.32   6.63 2.44
## 448     Yes      225.88   9.31 3.59
## 449      No      235.50   7.80 3.30
## 450     Yes      188.21  10.94 3.36
## 451     Yes      180.45   9.76 3.15
## 453     Yes      210.56   9.63 3.95
## 455      No      136.92   9.75 2.49
## 458      No      192.64  12.89 2.33
## 459      No      193.70  15.29 4.02
## 461      No      200.57   4.82 2.66
## 463      No      216.42   7.55 3.20
## 466     Yes      247.41   8.95 3.56
## 467     Yes      157.83  12.55 3.40
## 468      No      250.91   7.31 4.41
## 470      No      235.54   5.34 4.65
## 477      No      211.34   9.01 4.61
## 478     Yes      190.73   9.86 2.04
## 479      No      184.01  10.31 4.25
## 483      No      201.49   4.41 2.54
## 484      No      300.31   9.74 3.54
## 486     Yes      209.61  13.81 6.28
## 487      No      156.26   9.74 3.46
## 488      No      185.71   2.68 4.26
## 491     Yes      232.55  10.58 3.11
## 494      No      168.21  10.37 2.57
## 498      No      158.83  12.03 3.13
## 499      No      208.21   4.18 4.04
## 500      No      243.07  14.32 2.86
## 501      No      136.09   4.84 2.37
## 504      No      205.70   9.64 3.04
## 507      No      240.24  12.48 3.16
## 508      No      164.15   7.53 2.19
## 509      No      190.71   8.37 2.89
## 512      No      190.18   9.26 2.12
## 515      No      171.41  13.13 1.79
## 516      No      173.76   7.06 3.56
## 517     Yes      216.82   8.73 5.15
## 520      No      204.40   7.61 3.30
## 521      No      205.75   9.80 2.72
## 522      No      254.68   7.16 2.91
## 527      No      197.76   9.84 1.46
## 528      No      191.64  12.66 2.50
## 529     Yes      154.84   5.31 2.50
## 531      No      207.27  10.00 3.39
## 533     Yes      241.26   7.33 2.95
## 535      No      260.50  10.94 3.05
## 539      No      182.84   8.64 2.79
## 541     Yes      219.96   9.92 4.64
## 542      No      169.02   7.20 2.94
## 544      No      182.02  10.25 3.07
## 545     Yes      217.44  14.08 2.45
## 546     Yes      201.00   8.09 3.19
## 547      No      233.22   4.14 4.91
## 548      No      281.41  11.01 3.69
## 549      No      237.24   9.85 2.52
## 552     Yes      234.81  10.38 3.20
## 554      No      197.21  10.22 1.94
## 555      No      204.70   8.63 4.10
## 556     Yes      177.80   9.02 3.50
## 562      No      168.61   8.90 4.44
## 563      No      202.41  10.78 3.34
## 564      No      177.72  14.35 1.80
## 566     Yes      195.82  14.05 2.71
## 567      No      195.97   7.15 3.62
## 568     Yes      202.17   8.31 2.34
## 569      No      219.70   7.58 3.16
## 570      No      198.85  14.32 3.02
## 573      No      196.21   3.22 3.98
## 574     Yes      100.01  15.66 3.45
## 575      No      203.03   9.77 2.90
## 576      No      240.66  14.04 4.74
## 585      No      195.02   8.30 2.62
## 589     Yes      249.32   9.77 3.22
## 592      No      258.21  10.45 2.58
## 594      No      209.95  12.13 2.98
## 595      No      162.52   0.35 3.86
## 596      No      254.99   9.23 3.74
## 598     Yes      211.81   7.28 2.43
## 600     Yes      171.68  10.95 3.25
## 604      No      213.96   7.63 3.53
## 607      No      215.80   6.25 4.23
## 608     Yes      244.14  15.44 1.95
## 609      No      128.96  14.55 3.13
## 610      No      198.02  12.69 3.41
## 611      No      245.37   9.53 3.12
## 612      No      235.60   1.20 4.97
## 613      No      194.05   8.51 4.90
## 615      No      236.38  10.25 3.99
## 618      No      233.49   8.67 2.43
## 621      No      201.44   5.37 3.46
## 624      No      220.77   8.37 4.61
## 626      No      187.79  14.77 2.80
## 632      No      138.88   8.04 3.01
## 634     Yes      209.33  10.18 3.75
## 638      No      207.91   7.39 2.97
## 639      No      186.45  10.55 3.35
## 640     Yes      187.53  11.71 2.02
## 641      No      160.16  10.78 3.04
## 645      No      111.06  13.39 2.23
## 647      No      206.25   8.26 4.26
## 648      No      212.42   5.59 4.77
## 649      No      238.61   9.74 2.66
## 651      No      205.24   9.85 3.27
## 652      No      226.24   5.68 2.43
## 653     Yes      178.88   5.27 3.41
## 655     Yes      199.84   9.39 4.46
## 656      No      149.46  11.69 4.31
## 660      No      209.63   6.01 3.64
## 663      No      182.41   6.97 3.06
## 664     Yes      230.22  11.23 3.03
## 666      No      197.03  12.41 3.62
## 669      No      297.61   4.90 2.86
## 670      No      264.25   7.54 3.87
## 671      No      197.83   8.09 5.99
## 673      No      210.11   7.22 3.64
## 674     Yes      150.26  12.55 5.55
## 680      No      209.15   4.84 2.21
## 681     Yes      203.10   9.27 2.26
## 683     Yes      203.72   6.88 4.93
## 686      No      194.94  11.45 2.95
## 689     Yes      208.06   7.13 2.69
## 690     Yes      246.41   7.99 5.36
## 693      No      255.63   7.37 4.06
## 694      No      238.14  10.60 5.01
## 696      No      276.13   3.98 2.69
## 697     Yes      191.88  17.18 3.12
## 699      No      187.55   8.62 3.84
## 701      No      187.81   4.89 2.86
## 705      No      208.81   9.48 2.42
## 708     Yes      197.36   7.59 3.98
## 710      No      209.84   8.44 5.30
## 711      No      178.15   8.86 2.10
## 714      No      233.27   8.51 3.39
## 716     Yes      217.25   7.61 4.30
## 717      No      219.99  11.82 3.86
## 719     Yes      191.95  15.31 3.16
## 722      No      190.54  12.60 5.03
## 724      No      228.95   7.53 4.03
## 727      No      231.72  15.20 3.83
## 731      No      172.46  10.00 3.11
## 733      No      192.32   8.76 5.41
## 734      No      166.86   8.43 3.75
## 737      No      227.94   4.84 4.23
## 739      No      194.28   8.60 2.68
## 741     Yes      218.58  14.04 4.83
## 742     Yes      190.61  10.76 3.63
## 743     Yes      225.92   7.70 2.68
## 745     Yes      226.12   9.88 2.98
## 746      No      224.02   2.74 1.88
## 748     Yes      217.90  14.82 6.90
## 749     Yes      163.89   6.13 6.12
## 752     Yes      183.37   5.87 3.90
## 754      No      215.27   7.00 6.46
## 756      No      208.94   6.84 4.18
## 761      No      173.70  12.19 2.81
## 764      No      317.86   6.37 2.71
## 766      No      210.64   1.64 2.82
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{descDiabetes }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\StringTok{"variable"} \OtherTok{=} \FunctionTok{colnames}\NormalTok{(Diabetes\_B),}
                      \StringTok{"tipo"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\FunctionTok{rep}\NormalTok{(}\StringTok{"numerical"}\NormalTok{, }\DecValTok{8}\NormalTok{), }\FunctionTok{rep}\NormalTok{(}\StringTok{"categorical"}\NormalTok{, }\DecValTok{2}\NormalTok{), }\FunctionTok{rep}\NormalTok{(}\StringTok{"numerical"}\NormalTok{, }\DecValTok{3}\NormalTok{)),}
                      \StringTok{"descripción"} \OtherTok{=} \FunctionTok{c}\NormalTok{(}\StringTok{"Número de embarazos previos de la paciente"}\NormalTok{,}
                                        \StringTok{"Concentración de glucosa en plasma (mg/dL) tras una prueba de tolerancia oral"}\NormalTok{,}
                                        \StringTok{"Presión arterial diastólica (mm Hg)"}\NormalTok{,}
                                        \StringTok{"Grosor del pliegue cutáneo del tríceps (mm), utilizado para estimar la grasa corporal total"}\NormalTok{,}
                                        \StringTok{"Niveles de insulina sérica a las 2 horas de la prueba (𝜇g/ml)"}\NormalTok{,}
                                        \StringTok{"Índice de Masa Corporal"}\NormalTok{,}
                                        \StringTok{"Puntuación que sintetiza la carga genética basada en la historia familiar"}\NormalTok{,}
                                        \StringTok{"Edad de la paciente en años"}\NormalTok{,}
                                        \StringTok{"Estado del paciente con respecto a la diabetes (neg=Sano, pos=Afectado)"}\NormalTok{,}
                                        \StringTok{"Alimentación del paciente en base a una dieta vegana (Yes=Vegano, No=Dieta omnívora)"}\NormalTok{,}
                                        \StringTok{"Niveles de colesterol total en sangre (mg/dL)"}\NormalTok{,}
                                        \StringTok{"Niveles de leptina sérica (ng/mL). Hormona que regula la saciedad y el gasto energético"}\NormalTok{,}
                                        \StringTok{"Proteína C Reactiva en sangre (mg/L). Marcador de inflamación"}\NormalTok{), }\AttributeTok{stringsAsFactors =} \ConstantTok{FALSE}\NormalTok{)}
\FunctionTok{rownames}\NormalTok{(descDiabetes) }\OtherTok{=}\NormalTok{ descDiabetes}\SpecialCharTok{$}\NormalTok{variable}
\NormalTok{descDiabetes}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                variable        tipo
## pregnant       pregnant   numerical
## glucose         glucose   numerical
## pressure       pressure   numerical
## triceps         triceps   numerical
## insulin         insulin   numerical
## mass               mass   numerical
## pedigree       pedigree   numerical
## age                 age   numerical
## diabetes       diabetes categorical
## vegdiet         vegdiet categorical
## cholesterol cholesterol   numerical
## leptin           leptin   numerical
## CRP                 CRP   numerical
##                                                                                             descripción
## pregnant                                                     Número de embarazos previos de la paciente
## glucose                   Concentración de glucosa en plasma (mg/dL) tras una prueba de tolerancia oral
## pressure                                                            Presión arterial diastólica (mm Hg)
## triceps     Grosor del pliegue cutáneo del tríceps (mm), utilizado para estimar la grasa corporal total
## insulin                                   Niveles de insulina sérica a las 2 horas de la prueba (𝜇g/ml)
## mass                                                                            Índice de Masa Corporal
## pedigree                      Puntuación que sintetiza la carga genética basada en la historia familiar
## age                                                                         Edad de la paciente en años
## diabetes                        Estado del paciente con respecto a la diabetes (neg=Sano, pos=Afectado)
## vegdiet            Alimentación del paciente en base a una dieta vegana (Yes=Vegano, No=Dieta omnívora)
## cholesterol                                               Niveles de colesterol total en sangre (mg/dL)
## leptin          Niveles de leptina sérica (ng/mL). Hormona que regula la saciedad y el gasto energético
## CRP                                       Proteína C Reactiva en sangre (mg/L). Marcador de inflamación
\end{verbatim}

La base de datos tiene 371 observaciones iniciales.

\subsection{Análisis descriptivo}\label{anuxe1lisis-descriptivo}

\begin{verbatim}
##     pregnant         glucose         pressure         triceps     
##  Min.   : 0.000   Min.   : 56.0   Min.   : 24.00   Min.   : 7.00  
##  1st Qu.: 1.000   1st Qu.: 99.0   1st Qu.: 62.00   1st Qu.:21.00  
##  Median : 2.000   Median :119.0   Median : 70.00   Median :29.00  
##  Mean   : 3.272   Mean   :122.1   Mean   : 70.79   Mean   :28.93  
##  3rd Qu.: 5.000   3rd Qu.:143.0   3rd Qu.: 78.00   3rd Qu.:37.00  
##  Max.   :15.000   Max.   :198.0   Max.   :110.00   Max.   :63.00  
##     insulin           mass          pedigree           age      
##  Min.   : 14.0   Min.   :18.20   Min.   :0.0850   Min.   :21.0  
##  1st Qu.: 76.0   1st Qu.:28.40   1st Qu.:0.2685   1st Qu.:23.0  
##  Median :126.0   Median :33.20   Median :0.4460   Median :27.0  
##  Mean   :154.7   Mean   :33.06   Mean   :0.5215   Mean   :30.6  
##  3rd Qu.:190.0   3rd Qu.:37.05   3rd Qu.:0.6800   3rd Qu.:36.0  
##  Max.   :744.0   Max.   :67.10   Max.   :2.4200   Max.   :63.0  
##   cholesterol        leptin            CRP       
##  Min.   :100.0   Min.   : 0.350   Min.   :1.460  
##  1st Qu.:185.1   1st Qu.: 7.210   1st Qu.:2.860  
##  Median :203.8   Median : 8.860   Median :3.390  
##  Mean   :204.8   Mean   : 9.071   Mean   :3.539  
##  3rd Qu.:226.0   3rd Qu.:10.780   3rd Qu.:4.100  
##  Max.   :317.9   Max.   :17.180   Max.   :8.430
\end{verbatim}

\begin{verbatim}
## cholesterol    pressure        mass     glucose         CRP         age 
##   0.1569403   0.1764051   0.2127283   0.2538944   0.2824177   0.3216806 
##      leptin     triceps    pedigree     insulin    pregnant 
##   0.3262120   0.3615789   0.6681313   0.7367471   0.9647629
\end{verbatim}

\begin{verbatim}
##      diabetes vegdiet
## [1,]      248     254
## [2,]      123     117
\end{verbatim}

\begin{verbatim}
##      diabetes vegdiet
## [1,]    66.85   68.46
## [2,]    33.15   31.54
\end{verbatim}

Como todas las variables varian suficientemente, se las deja todas.

\includegraphics{PlantillaTrabajoAcademico1_files/figure-latex/boxplot-1.pdf}
\%\%\%\%\%\%\%\%\%\%\%\%\%\%\% IVAN
\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\%\% (por aqui empiezo,
siguiendo un poco la info d antes)

Una vez que hemos analizado las variables una por una (univariante) y
hemos comprobado la ausencia de valores faltantes y constantes, el
siguiente paso crítico en la preparación de una BBDD es entender
\textbf{cómo se relacionan las variables entre sí}. Esto nos permite
detectar dos cosas vitales:

1. \textbf{Redundancia (Colinealidad):} Si dos variables numéricas están
muy correlacionadas (proveen la misma información), podríamos eliminar
una de ellas para simplificar el modelo predictivo.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  \textbf{Asociación con el objetivo:} Observar si variables concretas
  discriminan bien nuestra variable objetivo (\texttt{diabetes}).
\end{enumerate}

\subsubsection{Matriz de Correlación}\label{matriz-de-correlaciuxf3n}

Las matrices de correlación nos calculan el coeficiente de Pearson entre
un abanico continuo de -1 (relación inversa total) a 1 (relación directa
total). Las correlaciones por encima de 0.7 nos advierten de
redundancias importantes.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# 1. Filtramos solo las variables que son numéricas}
\NormalTok{nums }\OtherTok{\textless{}{-}} \FunctionTok{sapply}\NormalTok{(Diabetes\_B, is.numeric)}
\NormalTok{data\_num }\OtherTok{\textless{}{-}}\NormalTok{ Diabetes\_B[, nums]}
\CommentTok{\# 2. Calculamos la matriz de correlación}
\NormalTok{cor\_mat }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(data\_num, }\AttributeTok{use =} \StringTok{"complete.obs"}\NormalTok{)}
\CommentTok{\# 3. Vamos a filtrar la matriz e imprimir solo las parejas con Correlación Mayor a 0.5 (Alta correlación)}
\NormalTok{cor\_mat[}\FunctionTok{lower.tri}\NormalTok{(cor\_mat, }\AttributeTok{diag=}\ConstantTok{TRUE}\NormalTok{)] }\OtherTok{\textless{}{-}} \ConstantTok{NA}
\NormalTok{high\_cor }\OtherTok{\textless{}{-}} \FunctionTok{which}\NormalTok{(}\FunctionTok{abs}\NormalTok{(cor\_mat) }\SpecialCharTok{\textgreater{}} \FloatTok{0.5}\NormalTok{, }\AttributeTok{arr.ind =} \ConstantTok{TRUE}\NormalTok{)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Parejas de Variables Altamente Correlacionadas}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Parejas de Variables Altamente Correlacionadas
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{(i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{nrow}\NormalTok{(high\_cor))\{}
    \FunctionTok{cat}\NormalTok{(}\FunctionTok{rownames}\NormalTok{(cor\_mat)[high\_cor[i,}\DecValTok{1}\NormalTok{]], }\StringTok{"{-}"}\NormalTok{, }\FunctionTok{colnames}\NormalTok{(cor\_mat)[high\_cor[i,}\DecValTok{2}\NormalTok{]], }
        \StringTok{":"}\NormalTok{, }\FunctionTok{round}\NormalTok{(cor\_mat[high\_cor[i,}\DecValTok{1}\NormalTok{], high\_cor[i,}\DecValTok{2}\NormalTok{]], }\DecValTok{2}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## glucose - insulin : 0.59 
## triceps - mass : 0.66 
## pregnant - age : 0.7 
## mass - CRP : 0.61
\end{verbatim}

\begin{itemize}
\item
  \texttt{pregnant\ -\ age\ :\ 0.70} A mayor edad, es predecible una
  mayor cantidad de embarazos en el histórico
\item
  \texttt{triceps\ -\ mass\ :\ 0.66} El grosor del pliegue cutáneo del
  tríceps avanza predeciblemente con la masa corporal general
\item
  \texttt{mass\ -\ CRP\ :\ 0.61} La proteína C Reactiva escala de la
  mano con el Índice de Masa Corporal
\item
  \texttt{glucose\ -\ insulin\ :\ 0.59} Niveles altos de glucosa
  correlacionan con niveles de insulina
\end{itemize}

La pareja \textbf{pregnant-age} se acerca al umbral crítico del
0.75-0.80, una de las dos variables podría llegar a eliminarse.

\#\#\#Análisis Bivariado Ahora vamos a visualizar rápidamente el
comportamiento que tienen las variables numéricas clave en función a
nuestra clase de interés: si el sujeto padece diabetes (positiva o
negativa).
\includegraphics{PlantillaTrabajoAcademico1_files/figure-latex/unnamed-chunk-2-1.pdf}

\begin{verbatim}
##   diabetes  glucose
## 1      neg 110.5565
## 2      pos 145.3496
\end{verbatim}

Al observar los diagramas que genera R y ver la tabla de medias de
glucosa (neg: 110.5, pos: 145.3), comprobamos de manera super evidente
que la \textbf{glucosa es un excelente predictor}. Los enfermos
diagnosticados positivamente tienen la línea base de la caja
notoriamente elevada y se superponen muy poco con el grueso de pacientes
negativos. La edad, sin embargo, muestra cajas mucho más solapadas
(impacta menos en el resultado global).

\#\#\#Análisis Bivariado (Categórica vs.~Categórica)

\begin{verbatim}
## --- Frecuencias Absolutas ---
\end{verbatim}

\begin{verbatim}
##      
##       neg pos
##   No  170  84
##   Yes  78  39
\end{verbatim}

\begin{verbatim}
## 
## --- Proporciones por Fila (Sabiendo la Dieta, ¿qué % es Diabético?) ---
\end{verbatim}

\begin{verbatim}
##      
##         neg   pos
##   No  66.93 33.07
##   Yes 66.67 33.33
\end{verbatim}

Se observa con este analisis que la variable \texttt{vegdiet} es
totalmente \textbf{inútil} para predecir si alguien tendrá diabetes.
Podría ser candidata a ser desechada sin afectar al aprendizaje general.

\section{Análisis de Componentes
Principales}\label{anuxe1lisis-de-componentes-principales}

\subsection{Tratamiento de los datos}\label{tratamiento-de-los-datos}

\begin{verbatim}
## Registered S3 method overwritten by 'quantmod':
##   method            from
##   as.zoo.data.frame zoo
\end{verbatim}

Para la ejecución del modelo PCA, se han seleccionado exclusivamente las
\emph{variables de naturaleza numérica}, ya que este análisis se basa en
el cálculo de varianzas y covarianzas que requieren datos continuos. Se
han excluido las variables categóricas, como la dieta (vegdiet) y el
diagnóstico final (diabetes), con el fin de que la estructura de las
componentes principales se construya únicamente a partir de los
biomarcadores metabólicos y antropométricos. Esto nos permitirá observar
cómo la variabilidad biológica de las pacientes agrupa los datos de
forma natural antes de contrastarlos con el diagnóstico real.

\begin{verbatim}
## Warning: To avoid problems with numeric identifiers, we added r prefix to the identifiers
\end{verbatim}

\begin{verbatim}
## Variables/Observaciones eliminadas:
\end{verbatim}

\begin{verbatim}
## $Variables
##       Variable Model Problem
## 1     pregnant              
## 2      glucose              
## 3     pressure              
## 4      triceps              
## 5      insulin              
## 6         mass              
## 7     pedigree              
## 8          age              
## 9  cholesterol              
## 10      leptin              
## 11         CRP              
## 
## $Observations
## [1] Observation Problem    
## <0 rows> (o 0- extensión row.names)
\end{verbatim}

Tras aplicar el filtrado, se confirma que la base de datos mantiene las
371 observaciones, lo que indica la ausencia de valores faltantes (NAs)
críticos que impidieran el análisis.

\begin{verbatim}
##     pregnant         glucose         pressure         triceps     
##  Min.   : 0.000   Min.   : 56.0   Min.   : 24.00   Min.   : 7.00  
##  1st Qu.: 1.000   1st Qu.: 99.0   1st Qu.: 62.00   1st Qu.:21.00  
##  Median : 2.000   Median :119.0   Median : 70.00   Median :29.00  
##  Mean   : 3.272   Mean   :122.1   Mean   : 70.79   Mean   :28.93  
##  3rd Qu.: 5.000   3rd Qu.:143.0   3rd Qu.: 78.00   3rd Qu.:37.00  
##  Max.   :15.000   Max.   :198.0   Max.   :110.00   Max.   :63.00  
##     insulin           mass          pedigree           age      
##  Min.   : 14.0   Min.   :18.20   Min.   :0.0850   Min.   :21.0  
##  1st Qu.: 76.0   1st Qu.:28.40   1st Qu.:0.2685   1st Qu.:23.0  
##  Median :126.0   Median :33.20   Median :0.4460   Median :27.0  
##  Mean   :154.7   Mean   :33.06   Mean   :0.5215   Mean   :30.6  
##  3rd Qu.:190.0   3rd Qu.:37.05   3rd Qu.:0.6800   3rd Qu.:36.0  
##  Max.   :744.0   Max.   :67.10   Max.   :2.4200   Max.   :63.0  
##   cholesterol        leptin            CRP       
##  Min.   :100.0   Min.   : 0.350   Min.   :1.460  
##  1st Qu.:185.1   1st Qu.: 7.210   1st Qu.:2.860  
##  Median :203.8   Median : 8.860   Median :3.390  
##  Mean   :204.8   Mean   : 9.071   Mean   :3.539  
##  3rd Qu.:226.0   3rd Qu.:10.780   3rd Qu.:4.100  
##  Max.   :317.9   Max.   :17.180   Max.   :8.430
\end{verbatim}

Como se observa en el resumen estadístico de los datos preparados, las
variables presentan rangos muy dispares (p.ej., la insulin varía entre
14 y 744, mientras que pedigree se mueve entre 0.08 y 2.42). Por ello,
aplicaremos un escalado unitario en el modelo para evitar que las
variables con magnitudes mayores dominen artificialmente la varianza del
modelo, permitiendo que cada biomarcador tenga el mismo peso específico.
\#\# Selección del número de componentes principales

\includegraphics{PlantillaTrabajoAcademico1_files/figure-latex/unnamed-chunk-9-1.pdf}

\subsection{Validación del modelo}\label{validaciuxf3n-del-modelo}

\subsection{Interpretación del
modelo}\label{interpretaciuxf3n-del-modelo}

\subsection{Conclusiones}\label{conclusiones}

\section{Reglas de asociación {[}OPCIONAL. 2 páginas
máximo{]}}\label{reglas-de-asociaciuxf3n-opcional.-2-puxe1ginas-muxe1ximo}

\section{Análisis Factorial de Correspondencias {[}OPCIONAL. 2 páginas
máximo{]}}\label{anuxe1lisis-factorial-de-correspondencias-opcional.-2-puxe1ginas-muxe1ximo}

\end{document}
